#!/bin/sh
#
OPTFILE="$HOME/.lpopts"

case "$1" in
  print)
    if [ -f $OPTFILE ] ; then
     OPTS=`grep -v '^#' $OPTFILE`
    else
     OPTS=""
    fi
    lpr $OPTS    
    ;;
  preview)
    TMPFILE=`mktemp`
    cat > $TMPFILE
    xmore $TMPFILE
    rm -f $TMPFILE
    ;;
  setup)
    if [ ! -f $OPTFILE ] ; then
      cat >$OPTFILE <<EOF
#
# Enter the LPR command arguments you want to use
#
EOF
    fi
    xedit $OPTFILE
    ;;
  *)
    echo "usage: $0 {print|preview|setup}"
esac
exit 0
