#!/bin/sh
# http://unlicense.org/

#=======================================
apps_to_check="$apps_to_check gettext"
extra_configure_opts="$extra_configure_opts gettext"
#=======================================

if [ -n "$PO2C_FILE" ] && [ -f "$PO2C_FILE" ] && [ -f po/po2c ] ; then
	PO2C_IS_AVAILABLE=yes
else
	PO2C_IS_AVAILABLE=no
fi


opt_print_gettext()
{
	echo '  --disable-nls           do not use Native Language Support (autodetect)'
}


opt_configure_gettext()
{
	USE_NLS='check'
	for i in $@
	do
		case $i in
		--enable-nls)  USE_NLS='yes' ;;
		--disable-nls) USE_NLS='no'  ; PO2C_IS_AVAILABLE='no' ;;
		po|pot)  # ./configure po|pot
			export GETTEXT_PACKAGE
			./po/zzpo.sh $1
			#sed -i '/#~ /d' po/*.po
			exit 0
			;;
		po2c)  # ./configure po2c
			[ -z "$PO2C_FILE" ] && PO2C_FILE="/dev/null"
			./po/po2c po/*.po > ${PO2C_FILE}
			exit $?
		esac
	done
}


opt_check_gettext()
{
	if [ "$USE_NLS" = "no" ] ; then
		make_extra_flags="$make_extra_flags
USE_NLS = no
GETTEXT_PACKAGE = $GETTEXT_PACKAGE"
		return
	fi

	echo -n "Checking for gettext... "
	ccode='#include <libintl.h>
#include <locale.h>
int main(void) {
	setlocale(LC_ALL, "");
	gettext("hi");
	return 0;
}
'
	w_compile_c_code "$ccode" "" ""
	if [ $? = 0 ] ; then
		echo "yes"
		USE_NLS='yes'
	else
		w_compile_c_code "$ccode" "" "-lintl"
		if [ $? = 0 ] ; then
			echo "yes (libintl)"
			LDFLAGS="$LDFLAGS -lintl"
		else
			echo "no"
			if [ "$USE_NLS" = "yes" ] ; then
				exit_error "Use --disable-nls"
			fi
			USE_NLS='no'
		fi
	fi

	if [ "$USE_NLS" = "no" ] ; then
		if [ "$PO2C_IS_AVAILABLE" = "yes" ] ; then
			echo "Language support will be built into the binary itself (po2c)"
		fi
		make_extra_flags="$make_extra_flags
USE_NLS = no
GETTEXT_PACKAGE = $GETTEXT_PACKAGE"
		return
	fi

	w_check_commands_required msgfmt

	LINGUASX="$(ls po/*.po | sed -e 's%\.po$%%' -e 's%po/%%')"

	# config.h
	localedir_x="$(eval echo "${localedir}")"
	localedir_x="$(eval echo "${localedir_x}")"
	config_h_extra="$config_h_extra
#define ENABLE_NLS 1
#define HAVE_GETTEXT 1
#define GETTEXT_PACKAGE \"$GETTEXT_PACKAGE\"
#define LOCALEDIR \"${localedir_x}\""

	# config.mk
	make_extra_flags="$make_extra_flags
USE_NLS = ${USE_NLS}
LINGUASX = $(echo $LINGUASX)
GETTEXT_PACKAGE = $GETTEXT_PACKAGE"

}
