#!/bin/sh
# http://unlicense.org/

#=======================================
apps_to_check="$apps_to_check gettext"
extra_configure_opts="$extra_configure_opts gettext"
#=======================================

if [ -n "$PO2C_FILE" ] && [ -f "$PO2C_FILE" ] && [ -f po/po2c ] ; then
	PO2C_IS_AVAILABLE=yes
else
	PO2C_IS_AVAILABLE=no
fi


opt_print_gettext()
{
	echo '  --disable-nls           do not use Native Language Support (autodetect)'
}


opt_configure_gettext()
{
	enable_gettext='check'
	for i in $@
	do
		case $i in
		--enable-nls)  enable_gettext='yes' ;;
		--disable-nls) enable_gettext='no'  ; PO2C_IS_AVAILABLE='no' ;;
		po|pot)  # ./configure po|pot
			export GETTEXT_PACKAGE
			./po/zzpo.sh $1
			#sed -i '/#~ /d' po/*.po
			exit 0
			;;
		po2c)  # ./configure po2c
			[ -z "$PO2C_FILE" ] && PO2C_FILE="/dev/null"
			./po/po2c po/*.po > ${PO2C_FILE}
			exit $?
		esac
	done
}


opt_check_gettext()
{
	if [ "$enable_gettext" = "no" ] ; then
		return
	fi

	printf "Checking for gettext... "
	ccode='#include <libintl.h>
#include <locale.h>
int main(void) {
	setlocale(LC_ALL, "");
	gettext("hi");
	return 0;
}
'
	w_compile_c_code "$ccode" "" ""
	if [ $? = 0 ] ; then
		echo "yes"
	else
		w_compile_c_code "$ccode" "" "-lintl"
		if [ $? = 0 ] ; then
			echo "yes (libintl)"
			LDFLAGS="$LDFLAGS -lintl"
		else
			echo "no"
			if [ "$enable_gettext" = "yes" ] ; then
				exit_error "Use --disable-nls"
			fi
			enable_gettext='no'
		fi
	fi

	if [ "$enable_gettext" = "yes" ] ; then
		w_check_commands_required msgfmt
	elif [ "$enable_gettext" = "check" ] ; then
		w_check_command msgfmt
		if [ $? -ne 0 ] ; then
			enable_gettext='no'
		fi
	fi

	if [ "$enable_gettext" = "no" ] ; then
		if [ "$PO2C_IS_AVAILABLE" = "yes" ] ; then
			echo "Language support will be built into the binary itself (po2c)"
			config_h_extra="$config_h_extra
#define BUILTIN_NLS 1"
			return
		fi
	fi

	LINGUAS="$(ls po/*.po | sed -e 's%\.po$%%' -e 's%po/%%')"

	config_h_extra="$config_h_extra
#define HAVE_GETTEXT 1
#define GETTEXT_PACKAGE \"$GETTEXT_PACKAGE\""

	# config.mk
	make_extra_flags="$make_extra_flags
USE_NLS = yes
LINGUAS = $(echo $LINGUAS)
GETTEXT_PACKAGE = $GETTEXT_PACKAGE
"
}
