#!/bin/sh
# https://unlicense.org

#
# param:
#       mo  - create mo files, `rm *.mo` to update
#       pot - update pot file
#       po  - update pot file + pot files
#

cd $(dirname "$0")

get_linguas()
{
	if [ -z "$LINGUAS" ] ; then
		LINGUAS="$(ls *.po | sed 's/\.po$//')"
	fi
	if [ -z "$LINGUAS" ] ; then
		echo "-- There no .po files --"
		exit 0
	fi
}

get_pot_source_files()
{
	if [ -z "$POT_SOURCE_FILES" ] ; then
		filez=$(find .. -type f -name '*.h' -or -name '*.c' -or -name '*.cc' -or -name '*.cpp' -or -name '*.hh')
		if [ -z "$filez" ] ; then
			echo "-- No source files have been translated --"
			exit 0
		fi
	fi
	#--
	POT_SOURCE_FILES="$(grep '_(' $filez | sed -e 's%^\./%%' -e 's%:.*%%' | sort -u)"
	echo "# generated by zzpo.sh" >  POTFILES
	echo "# this file is only used as a reference to notice if something has changed" >>  POTFILES
	echo "$POT_SOURCE_FILES" >> POTFILES
}

get_gettext_package()
{
	if [ -z "$GETTEXT_PACKAGE" ] ; then
		GETTEXT_PACKAGE=$(ls *.pot | head -n 1 | sed 's%.pot%%')
		if [ -z "$GETTEXT_PACKAGE" ] ; then
			echo ".pot file is missing"
			exit 1
		fi
	fi
}

#==========================================================================

update_pot()
{
	if [ -z "$XGETTEXT" ] ; then
		XGETTEXT=xgettext
	fi
	get_pot_source_files
	get_gettext_package
	#--
	echo "GETTEXT_PACKAGE: ${GETTEXT_PACKAGE}.pot"
	${XGETTEXT} \
		--default-domain=${GETTEXT_PACKAGE} \
		--add-comments \
		--keyword=_ \
		--keyword=N_ \
		--from-code=UTF-8 \
		-o ${GETTEXT_PACKAGE}.pot2 ${POT_SOURCE_FILES}

	if [ $? -eq 0 ] ; then
		mv ${GETTEXT_PACKAGE}.pot2 ${GETTEXT_PACKAGE}.pot
	else
		rm -f ${GETTEXT_PACKAGE}.pot2
		exit 1
	fi
}


update_po()
{
	if [ -z "$MSGMERGE" ] ; then
		MSGMERGE=msgmerge
	fi
	get_linguas
	get_gettext_package
	#--
	for lang in ${LINGUAS}
	do
		printf " %s " "$lang";
		if ${MSGMERGE} ${lang}.po ${GETTEXT_PACKAGE}.pot -o ${lang}.new.po; then
			mv -f ${lang}.new.po ${lang}.po || exit 1;
		else
			echo "msgmerge for $lang failed!";
			rm -f ${lang}.new.po;
		fi;
	done
	exit
}


build_mo()
{
	get_linguas
	if [ -z "$MSGFMT" ] ; then
		MSGFMT=msgfmt
	fi
	# --
	for i in ${LINGUAS} ; do
		if ! test -f ${i}.mo ; then
			echo "${MSGFMT} -o ${i}.mo ${i}.po"
			${MSGFMT} -o ${i}.mo ${i}.po
		fi
	done
}

#==========================================================================

case $1 in *msgfmt*)
	MSGFMT=$1
	XGETTEXT=$2
	MSGMERGE=$3
	shift
	shift
	shift
	;;
esac


case "$1" in
	pot)
		shift
		GETTEXT_PACKAGE="$1"
		update_pot
		exit $?
		;;
	po)
		shift
		GETTEXT_PACKAGE=$1
		shift
		LINGUAS="$@"
		#--
		update_pot
		update_po
		exit $?
		;;
	mo)
		shift
		LINGUAS="$@"
		#--
		build_mo
		exit $?
		;;
	*)
		echo "unrecognized command: $1"
		exit 1
		;;
esac

